export const FIVE_MINUTES_IN_SECONDS = 300;
export const TEN_MINUTES_IN_SECONDS = 600;
export const FIFTEEN_MINUTES_IN_SECONDS = 900;
export const ONE_HOUR_IN_SECONDS = 3600;
export const FOUR_HOURS_IN_SECONDS = 14400;
export const TWELVE_HOURS_IN_SECONDS = 43200;
